// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1vn-UpdHqKxu0pCTecAKXPdpW43CahJo',
    appId: '1:39167775796:web:f117e9ea8e9970dff3a661',
    messagingSenderId: '39167775796',
    projectId: 'blood-donation-app-400e1',
    authDomain: 'blood-donation-app-400e1.firebaseapp.com',
    storageBucket: 'blood-donation-app-400e1.firebasestorage.app',
    measurementId: 'G-SZL9GCKB7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4oIsUuy8ON8__2Is4W62VBX19ppxW6VM',
    appId: '1:39167775796:android:711dd0e518ab1ea1f3a661',
    messagingSenderId: '39167775796',
    projectId: 'blood-donation-app-400e1',
    storageBucket: 'blood-donation-app-400e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE3JmBIzsdMK7BHWrlLaC1hwJ93n06WDw',
    appId: '1:39167775796:ios:1f4aace6c6d9fa7bf3a661',
    messagingSenderId: '39167775796',
    projectId: 'blood-donation-app-400e1',
    storageBucket: 'blood-donation-app-400e1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE3JmBIzsdMK7BHWrlLaC1hwJ93n06WDw',
    appId: '1:39167775796:ios:1f4aace6c6d9fa7bf3a661',
    messagingSenderId: '39167775796',
    projectId: 'blood-donation-app-400e1',
    storageBucket: 'blood-donation-app-400e1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1vn-UpdHqKxu0pCTecAKXPdpW43CahJo',
    appId: '1:39167775796:web:d814798af92bf349f3a661',
    messagingSenderId: '39167775796',
    projectId: 'blood-donation-app-400e1',
    authDomain: 'blood-donation-app-400e1.firebaseapp.com',
    storageBucket: 'blood-donation-app-400e1.firebasestorage.app',
    measurementId: 'G-NY7YR2SVDE',
  );
}
